"use server";

import React from "react";
import { randomUUID } from "crypto";
import { PutObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import {
  generateProgram,
  buildProgramPreviewFromBlueprint,
  type GeneratedProgram,
} from "@/lib/services/ai.service";
import {
  extractProgramBriefText,
  extractBriefMetadata,
  parseProgramBrief,
  type BriefMetadata,
  type ProgramBriefParsed,
} from "@/lib/services/program-brief.service";
import { generatedProgramSchema } from "@/lib/validators/generated-program";
import {
  categorizeGeneratedProgram,
  buildCategorizationContextFromParams,
} from "@/lib/services/program-categorization.service";

import { auth } from "@clerk/nextjs/server";
import { prisma } from "@/lib/prisma";
import { getResend } from "@/lib/email/resend";
import { ShareProgramEmail } from "@/lib/email/templates/share-program";
import { parseShareRecipients } from "./program-share-helpers";
import { revalidatePath } from "next/cache";
import * as programService from "@/lib/services/program.service";
import { recordExerciseUsage } from "@/lib/services/exercise.service";
import { getR2Client, R2_BUCKET_NAME, R2_PUBLIC_URL } from "@/lib/r2";
import {
  presignSchema as programBriefPresignSchema,
  CONTENT_TYPES as PROGRAM_BRIEF_CONTENT_TYPES,
} from "@/lib/validators/program-brief";
import {
  createProgramSchema,
  updateProgramSchema,
  assignProgramSchema,
} from "@/lib/validators/program";
import type {
  CreateProgramInput,
  UpdateProgramInput,
} from "@/lib/validators/program";
import type { WeekPlan } from "@/lib/ai/types/program-generation";
import { logAudit, diffFields, deriveActorType, AUDIT_ACTIONS } from "@/lib/services/audit-log.service";
import { getClientIdsForTrainer } from "@/lib/services/client.service";

async function getTrainerUser() {
  const { userId } = await auth();
  if (!userId) return null;
  const dbUser = await prisma.user.findUnique({ where: { clerkId: userId } });
  if (!dbUser || dbUser.role !== "TRAINER") return null;
  return dbUser;
}

async function createProgramFromGeneratedPlan(params: {
  aiPlan: GeneratedProgram;
  trainerId: string | null;
  isGlobal?: boolean;
  isTemplate: boolean;
  aiGenerationParams: Record<string, unknown>;
  clientId?: string | null;
  startDate?: string | null;
}) {
  const { aiPlan, trainerId, isTemplate, aiGenerationParams, clientId, startDate } = params;

  const validation = generatedProgramSchema.safeParse(aiPlan);
  if (!validation.success) {
    throw new Error(`Invalid generated program: ${validation.error.issues[0].message}`);
  }

  const sDate = startDate
    ? (() => { const [y, m, d] = startDate.split("-").map(Number); return new Date(y, m - 1, d); })()
    : null;

  const durationWeeks = programService.computeDurationWeeksFromWorkouts(aiPlan.workouts);
  const daysPerWeek =
    typeof aiGenerationParams.daysPerWeek === "number" ? aiGenerationParams.daysPerWeek : null;

  const categorization = await categorizeGeneratedProgram(
    aiPlan,
    buildCategorizationContextFromParams(aiGenerationParams)
  );

  // Round 1: program shell only — no nested creates
  const program = await prisma.program.create({
    data: {
      name: aiPlan.name,
      description: aiPlan.description || "Generated by AI",
      isTemplate: !clientId && isTemplate,
      isGlobal: params.isGlobal ?? false,
      trainerId,
      clientId: clientId ?? null,
      status: clientId ? "ACTIVE" : "DRAFT",
      programType: typeof aiGenerationParams.programMode === "string" ? aiGenerationParams.programMode : null,
      durationWeeks,
      daysPerWeek,
      startDate: sDate ?? undefined,
      aiGenerationParams: aiGenerationParams as import("@prisma/client").Prisma.InputJsonValue,
      bodyAreas: categorization.bodyAreas,
      goals: categorization.goals,
      activities: categorization.activities,
      level: categorization.level ?? undefined,
      tags: categorization.tags,
    },
    select: { id: true },
  });

  // Round 2: all workouts in parallel
  const createdWorkouts = await Promise.all(
    aiPlan.workouts.map((w) =>
      prisma.workout.create({
        data: {
          programId: program.id,
          name: w.name,
          dayIndex: w.dayIndex,
          weekIndex: w.weekIndex ?? 0,
          orderIndex: (w.weekIndex ?? 0) * 7 + w.dayIndex,
        },
        select: { id: true, dayIndex: true },
      })
    )
  );

  // Round 3: all blocks in parallel — flat list keyed by workout index
  const blockInputs = aiPlan.workouts.flatMap((w, wi) =>
    w.blocks.map((b) => ({ workoutId: createdWorkouts[wi].id, block: b }))
  );
  const createdBlocks = await Promise.all(
    blockInputs.map(({ workoutId, block: b }) =>
      prisma.workoutBlockV2.create({
        data: {
          workoutId,
          type: b.type || "NORMAL",
          name: b.name || b.type || "NORMAL",
          orderIndex: b.orderIndex,
          rounds: b.rounds ?? 1,
          restBetweenRounds: b.restBetweenRounds ?? null,
        },
        select: { id: true },
      })
    )
  );

  // Round 4: all exercises in parallel — flat list keyed by block index
  const exerciseInputs = blockInputs.flatMap(({ block: b }, bi) =>
    b.exercises.map((e) => ({ blockId: createdBlocks[bi].id, exercise: e }))
  );
  const createdExercises = await Promise.all(
    exerciseInputs.map(({ blockId, exercise: e }) =>
      prisma.blockExerciseV2.create({
        data: {
          blockId,
          exerciseId: e.exerciseId,
          orderIndex: e.orderIndex,
          notes: e.notes ?? null,
          restSeconds: e.restSeconds ?? null,
        },
        select: { id: true },
      })
    )
  );

  // Round 5: all sets in ONE createMany — fastest possible for the bulk records
  const allSets = exerciseInputs.flatMap(({ exercise: e }, ei) => {
    const repStr = e.reps?.toString() ?? "10";
    const isDuration = repStr.endsWith("s");
    const targetReps = isDuration ? null : parseInt(repStr, 10) || null;
    const targetDuration = isDuration ? parseInt(repStr.replace("s", ""), 10) || null : null;
    return Array.from({ length: Math.max(1, e.sets || 1) }).map((_, i) => ({
      blockExerciseId: createdExercises[ei].id,
      orderIndex: i,
      setType: "NORMAL" as const,
      ...(targetReps !== null ? { targetReps } : {}),
      ...(targetDuration !== null ? { targetDuration } : {}),
    }));
  });
  if (allSets.length > 0) {
    await prisma.exerciseSet.createMany({ data: allSets });
  }

  // Round 6: sessions if assigning — single createMany
  if (clientId && sDate) {
    // Build a map from createdWorkout id → aiPlan workout (to get weekIndex)
    const workoutWeekMap = new Map<string, number>(
      aiPlan.workouts.map((w, i) => [createdWorkouts[i].id, w.weekIndex ?? 0])
    );
    await prisma.workoutSessionV2.createMany({
      data: createdWorkouts.map((w) => {
        const weekIdx = workoutWeekMap.get(w.id) ?? 0;
        const d = new Date(sDate);
        d.setDate(d.getDate() + weekIdx * 7 + w.dayIndex);
        return { workoutId: w.id, clientId, scheduledDate: d, status: "SCHEDULED" as const };
      }),
    });
  }

  return program;
}

export async function createProgramAction(input: CreateProgramInput) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  const parsed = createProgramSchema.safeParse(input);
  if (!parsed.success) {
    return { success: false as const, error: parsed.error.issues[0].message };
  }

  try {
    const program = await programService.createProgram(user.id, parsed.data);
    await logAudit({
      actorId: user.id,
      actorType: deriveActorType(user),
      actorName: `${user.firstName} ${user.lastName}`,
      action: AUDIT_ACTIONS.PROGRAM_CREATED,
      targetType: "Program",
      targetId: program.id,
      targetLabel: program.name,
      orgId: user.clerkOrgId,
    });
    try {
      await recordExerciseUsage(user.id, parsed.data.workouts);
    } catch (error) {
      console.error("Failed to record exercise usage:", error);
    }
    revalidatePath("/programs");
    return { success: true as const, data: program };
  } catch (error) {
    console.error("Failed to create program:", error);
    return { success: false as const, error: "Failed to create program" };
  }
}

export async function updateProgramAction(
  programId: string,
  input: UpdateProgramInput
) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  const program = await prisma.program.findUnique({
    where: { id: programId },
    select: { trainerId: true, name: true, description: true, status: true },
  });
  if (!program || program.trainerId !== user.id) {
    return { success: false as const, error: "Forbidden" };
  }

  const parsed = updateProgramSchema.safeParse(input);
  if (!parsed.success) {
    return { success: false as const, error: parsed.error.issues[0].message };
  }

  try {
    const updated = await programService.updateProgram(programId, parsed.data);
    const diff = diffFields(
      program as unknown as Record<string, unknown>,
      parsed.data as unknown as Record<string, unknown>,
      ["name", "description", "status"]
    );
    await logAudit({
      actorId: user.id,
      actorType: deriveActorType(user),
      actorName: `${user.firstName} ${user.lastName}`,
      action: AUDIT_ACTIONS.PROGRAM_UPDATED,
      targetType: "Program",
      targetId: programId,
      targetLabel: updated.name,
      orgId: user.clerkOrgId,
      metadata: diff,
    });
    if (parsed.data.workouts) {
      try {
        await recordExerciseUsage(user.id, parsed.data.workouts);
      } catch (error) {
        console.error("Failed to record exercise usage:", error);
      }
    }
    revalidatePath("/programs");
    revalidatePath(`/programs/${programId}`);
    return { success: true as const, data: updated };
  } catch (error) {
    console.error("Failed to update program:", error);
    return { success: false as const, error: "Failed to update program" };
  }
}

export async function deleteProgramAction(programId: string) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  const program = await prisma.program.findUnique({
    where: { id: programId },
    select: { trainerId: true, name: true },
  });
  if (!program || program.trainerId !== user.id) {
    return { success: false as const, error: "Forbidden" };
  }

  try {
    await programService.deleteProgram(programId);
    await logAudit({
      actorId: user.id,
      actorType: deriveActorType(user),
      actorName: `${user.firstName} ${user.lastName}`,
      action: AUDIT_ACTIONS.PROGRAM_DELETED,
      targetType: "Program",
      targetId: programId,
      targetLabel: program.name,
      orgId: user.clerkOrgId,
    });
    revalidatePath("/programs");
    return { success: true as const };
  } catch (error) {
    console.error("Failed to delete program:", error);
    return { success: false as const, error: "Failed to delete program" };
  }
}

export async function hardDeleteProgramAction(programId: string) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  const program = await prisma.program.findUnique({
    where: { id: programId },
    select: { trainerId: true, name: true },
  });
  if (!program || program.trainerId !== user.id) {
    return { success: false as const, error: "Forbidden" };
  }

  try {
    await programService.hardDeleteProgram(programId);
    await logAudit({
      actorId: user.id,
      actorType: deriveActorType(user),
      actorName: `${user.firstName} ${user.lastName}`,
      action: AUDIT_ACTIONS.PROGRAM_HARD_DELETED,
      targetType: "Program",
      targetId: programId,
      targetLabel: program.name,
      orgId: user.clerkOrgId,
    });
    revalidatePath("/programs");
    return { success: true as const };
  } catch (error) {
    console.error("Failed to permanently delete program:", error);
    const message =
      error instanceof Error && error.message.startsWith("Cannot delete:")
        ? error.message
        : "Failed to permanently delete program";
    return { success: false as const, error: message };
  }
}

export async function toggleProgramPublicAction(programId: string, isPublic: boolean) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  const program = await prisma.program.findUnique({
    where: { id: programId },
    select: { trainerId: true, name: true, isTemplate: true, clientId: true },
  });
  if (!program || program.trainerId !== user.id) {
    return { success: false as const, error: "Forbidden" };
  }
  if (!program.isTemplate || program.clientId) {
    return {
      success: false as const,
      error: "Only templates with no client assigned can be made public",
    };
  }

  try {
    await programService.toggleProgramPublic(programId, isPublic);
    await logAudit({
      actorId: user.id,
      actorType: deriveActorType(user),
      actorName: `${user.firstName} ${user.lastName}`,
      action: AUDIT_ACTIONS.PROGRAM_UPDATED,
      targetType: "Program",
      targetId: programId,
      targetLabel: program.name,
      orgId: user.clerkOrgId,
      metadata: { isPublic },
    });
    revalidatePath("/programs");
    return { success: true as const };
  } catch (error) {
    console.error("Failed to toggle program public:", error);
    return { success: false as const, error: "Failed to update program" };
  }
}

export async function duplicateProgramAction(
  programId: string,
  asTemplate = false
) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  try {
    const program = await programService.duplicateProgram(
      programId,
      user.id,
      asTemplate
    );
    revalidatePath("/programs");
    return { success: true as const, data: program };
  } catch (error) {
    console.error("Failed to duplicate program:", error);
    return { success: false as const, error: "Failed to duplicate program" };
  }
}

export async function assignProgramAction(input: {
  programId: string;
  clientId: string;
  startDate: string;
}) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  const parsed = assignProgramSchema.safeParse(input);
  if (!parsed.success) {
    return { success: false as const, error: parsed.error.issues[0].message };
  }

  const program = await prisma.program.findUnique({
    where: { id: parsed.data.programId },
    select: { trainerId: true },
  });
  if (!program || program.trainerId !== user.id) {
    return { success: false as const, error: "Forbidden" };
  }

  const clientIds = await getClientIdsForTrainer(user.id);
  if (!clientIds.includes(parsed.data.clientId)) {
    return { success: false as const, error: "Forbidden" };
  }

  try {
    // Assigning a template must never mutate the template row itself — clone
    // it into a standalone program first, then attach the client/start date
    // to the clone. Otherwise the template loses isTemplate/clientId=null and
    // can't be assigned to a second client afterward.
    const copy = await programService.duplicateProgram(
      parsed.data.programId,
      user.id,
      false
    );
    const result = await programService.assignProgram(
      copy.id,
      parsed.data.clientId,
      new Date(parsed.data.startDate)
    );
    revalidatePath("/programs");
    revalidatePath(`/programs/${parsed.data.programId}`);
    revalidatePath(`/clients/${parsed.data.clientId}`);
    revalidatePath("/dashboard");
    return { success: true as const, data: result };
  } catch (error) {
    console.error("Failed to assign program:", error);
    return { success: false as const, error: "Failed to assign program" };
  }
}

export async function syncProgramToMasterAction(programId: string) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  const program = await prisma.program.findUnique({
    where: { id: programId },
    select: { trainerId: true, sourceTemplateId: true },
  });
  if (!program || program.trainerId !== user.id) {
    return { success: false as const, error: "Forbidden" };
  }
  if (!program.sourceTemplateId) {
    return { success: false as const, error: "This program isn't linked to a master template" };
  }

  try {
    const updated = await programService.syncProgramToTemplate(programId, user.id);
    await logAudit({
      actorId: user.id,
      actorType: deriveActorType(user),
      actorName: `${user.firstName} ${user.lastName}`,
      action: AUDIT_ACTIONS.PROGRAM_UPDATED,
      targetType: "Program",
      targetId: updated.id,
      targetLabel: updated.name,
      orgId: user.clerkOrgId,
      metadata: { syncedFromAssignedProgramId: programId },
    });
    revalidatePath("/programs");
    revalidatePath(`/programs/${updated.id}`);
    return { success: true as const, data: updated };
  } catch (error) {
    console.error("Failed to sync program to master template:", error);
    return { success: false as const, error: "Failed to save changes to master program" };
  }
}

export async function toggleProgramFavoriteAction(programId: string, isFavorite: boolean) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  const program = await prisma.program.findUnique({
    where: { id: programId },
    select: { trainerId: true },
  });
  if (!program || program.trainerId !== user.id) {
    return { success: false as const, error: "Forbidden" };
  }

  try {
    const updated = await programService.toggleProgramFavorite(programId, isFavorite);
    revalidatePath("/programs");
    return { success: true as const, data: updated };
  } catch (error) {
    console.error("Failed to toggle program favorite:", error);
    return { success: false as const, error: "Failed to update favorite" };
  }
}

export async function setProgramCollectionsAction(programId: string, collectionIds: string[]) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  const program = await prisma.program.findUnique({
    where: { id: programId },
    select: { trainerId: true },
  });
  if (!program || program.trainerId !== user.id) {
    return { success: false as const, error: "Forbidden" };
  }

  try {
    const updated = await programService.setProgramCollections(programId, collectionIds);
    revalidatePath("/programs");
    return { success: true as const, data: updated };
  } catch (error) {
    console.error("Failed to update program collections:", error);
    return { success: false as const, error: "Failed to update collections" };
  }
}

export async function deleteClientProgramAction(programId: string) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  const program = await prisma.program.findUnique({
    where: { id: programId },
    select: { trainerId: true, name: true, clientId: true },
  });
  if (!program || program.trainerId !== user.id) {
    return { success: false as const, error: "Forbidden" };
  }
  if (!program.clientId) {
    return { success: false as const, error: "This program is not assigned to a client" };
  }

  try {
    await programService.deleteClientProgram(programId);
    await logAudit({
      actorId: user.id,
      actorType: deriveActorType(user),
      actorName: `${user.firstName} ${user.lastName}`,
      action: AUDIT_ACTIONS.PROGRAM_HARD_DELETED,
      targetType: "Program",
      targetId: programId,
      targetLabel: program.name,
      orgId: user.clerkOrgId,
    });
    revalidatePath(`/clients/${program.clientId}`);
    revalidatePath("/dashboard");
    revalidatePath("/programs");
    return { success: true as const };
  } catch (error) {
    console.error("Failed to delete client program:", error);
    const message =
      error instanceof Error && error.message.startsWith("Cannot delete:")
        ? error.message
        : "Failed to delete program";
    return { success: false as const, error: message };
  }
}

export async function getProgramsAction(filters?: {
  search?: string;
  status?: string;
  isTemplate?: boolean;
}) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  try {
    const programs = await programService.getPrograms(user.id, filters
      ? { ...filters, status: filters.status as import("@prisma/client").PlanStatus | undefined }
      : undefined);
    return { success: true as const, data: programs };
  } catch (error) {
    console.error("Failed to fetch programs:", error);
    return { success: false as const, error: "Failed to fetch programs" };
  }
}

export async function getProgramAction(programId: string) {
  const { userId } = await auth();
  if (!userId) return { success: false as const, error: "Unauthorized" };

  const dbUser = await prisma.user.findUnique({ where: { clerkId: userId } });
  if (!dbUser) return { success: false as const, error: "User not found" };

  try {
    const program = await programService.getProgramById(programId);
    if (!program)
      return { success: false as const, error: "Program not found" };

    if (program.trainerId !== dbUser.id && program.clientId !== dbUser.id) {
      return { success: false as const, error: "Forbidden" };
    }

    return { success: true as const, data: program };
  } catch (error) {
    console.error("Failed to fetch program:", error);
    return { success: false as const, error: "Failed to fetch program" };
  }
}


export async function generateProgramAction(
  params: {
    clientId?: string | null;
    startDate?: string | null;
    durationWeeks?: number;          // NEW
    weekPlan?: WeekPlan[];           // NEW
    [key: string]: unknown;
  }
) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  if (params.clientId) {
    const clientIds = await getClientIdsForTrainer(user.id);
    if (!clientIds.includes(params.clientId)) {
      return { success: false as const, error: "Forbidden" };
    }
  }

  try {
    const aiPlan = await generateProgram({
      ...params,
      weekPlan: params.weekPlan,
      durationWeeks: params.durationWeeks,
    } as Parameters<typeof generateProgram>[0]);
    const program = await createProgramFromGeneratedPlan({
      aiPlan,
      trainerId: user.id,
      isTemplate: false,
      aiGenerationParams: params,
      clientId: params.clientId || null,
      startDate: params.clientId
        ? (params.startDate ?? new Date().toISOString().split("T")[0])
        : null,
    });

    revalidatePath("/programs");
    if (params.clientId) revalidatePath(`/clients/${params.clientId}`);
    return { success: true as const, data: program.id };
  } catch (error) {
    console.error("Failed to generate program:", error);
    const message =
      error instanceof Error && error.message.startsWith("Invalid generated program:")
        ? error.message
        : "Failed to generate program";
    return { success: false as const, error: message };
  }
}

export async function generateProgramBriefUploadUrlAction(
  fileExtension: string
): Promise<{
  success: boolean;
  data?: { presignedUrl: string; fileUrl: string; contentType: string };
  error?: string;
}> {
  const user = await getTrainerUser();
  if (!user) return { success: false, error: "Unauthorized" };

  const parsed = programBriefPresignSchema.safeParse({ fileExtension });
  if (!parsed.success) {
    return { success: false, error: "Only PDF, DOCX, TXT, or Markdown files are supported" };
  }

  try {
    const contentType = PROGRAM_BRIEF_CONTENT_TYPES[parsed.data.fileExtension];
    const key = `program-briefs/${user.id}/${randomUUID()}.${parsed.data.fileExtension}`;
    const command = new PutObjectCommand({
      Bucket: R2_BUCKET_NAME,
      Key: key,
      ContentType: contentType,
    });
    const presignedUrl = await getSignedUrl(getR2Client(), command, { expiresIn: 300 });

    return {
      success: true,
      data: { presignedUrl, fileUrl: `${R2_PUBLIC_URL}/${key}`, contentType },
    };
  } catch (error) {
    console.error("[program-brief] presign error:", error);
    return { success: false, error: "Failed to generate upload URL" };
  }
}

// Step 1 of the brief-upload flow: read the document and extract only the
// high-level metadata (title, difficulty, duration, focus areas, schedule).
// Schedule (daysPerWeek/preferredWeekdays) is the one piece that actually
// gets baked into the generated program's day assignments — if the document
// didn't state it, the trainer needs to confirm it BEFORE generation runs,
// not after, since editing it afterward wouldn't move anything. The caller
// checks `metadata.inferredFields` for "estimatedDaysPerWeek" /
// "preferredWeekdays" to decide whether to show a confirmation step before
// calling extractProgramChunksAction/matchProgramExercisesAction.
const REQUIRED_BRIEF_METADATA_FIELDS = ["programTitle", "estimatedDaysPerWeek", "preferredWeekdays"] as const;

export async function extractProgramMetadataFromBriefAction(input: {
  fileUrl: string;
  fileName: string;
}) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  try {
    const rawText = await extractProgramBriefText(input.fileUrl, input.fileName);
    if (!rawText.trim()) {
      return { success: false as const, error: "The document appears to be empty or unreadable." };
    }
    const metadata = await extractBriefMetadata(rawText);
    const missingRequiredFields = REQUIRED_BRIEF_METADATA_FIELDS.filter((f) =>
      metadata.inferredFields.includes(f)
    );
    return { success: true as const, data: { metadata, rawText, missingRequiredFields } };
  } catch (error) {
    console.error("Failed to extract program metadata from brief:", error);
    return { success: false as const, error: "Failed to read this document" };
  }
}

// Stage 2 of the brief-upload flow: chunk + extract every session/exercise
// from the full document. No exercise-library matching happens here — that's
// stage 3 (matchProgramExercisesAction) — so this stays fast and its result
// can be shown as its own progress step.
export async function extractProgramChunksAction(input: {
  rawText: string;
  metadata: BriefMetadata;
}) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  try {
    const parsed = await parseProgramBrief(input.rawText, input.metadata);
    if (!parsed.ok) {
      return { success: false as const, error: parsed.errors.join("\n") };
    }
    return { success: true as const, data: parsed.data };
  } catch (error) {
    console.error("Failed to extract program chunks from brief:", error);
    return { success: false as const, error: "Failed to extract program structure from this document" };
  }
}

// Stage 3: deterministically match every extracted exercise against the
// exercise library (no LLM calls) and return a preview where unmatched or
// low-confidence exercises carry `flags` instead of being silently
// substituted or dropped.
export async function matchProgramExercisesAction(input: {
  brief: ProgramBriefParsed;
}) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  try {
    const brief = input.brief;
    if (!brief.sessionBlueprint?.length) {
      return { success: false as const, error: "No training sessions were found to match exercises for" };
    }

    const params = {
      programTitle: brief.programTitle,
      focusAreas: brief.focusAreas,
      durationMinutes: brief.durationMinutes,
      daysPerWeek: brief.daysPerWeek,
      circuits: brief.circuits.map((c) => ({
        name: c.name,
        focusType: c.focusType,
        exerciseCount: c.exerciseCount,
        rounds: c.rounds,
      })),
      difficultyLevel: brief.difficultyLevel,
      preferredWeekdays: brief.preferredWeekdays,
      sessionBlueprint: brief.sessionBlueprint,
    };

    const preview = await buildProgramPreviewFromBlueprint(params);

    return {
      success: true as const,
      data: {
        preview,
        params,
        parsed: brief,
        warnings: Array.from(new Set(brief.warnings ?? [])),
      },
    };
  } catch (error) {
    console.error("Failed to match exercises for brief:", error);
    return { success: false as const, error: "Failed to match exercises against your exercise library" };
  }
}

export async function saveGeneratedProgramAction(input: {
  aiPlan: GeneratedProgram;
  params: Record<string, unknown>;
  isTemplate: boolean;
  clientId?: string | null;
  startDate?: string;
}) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  if (input.clientId) {
    const clientIds = await getClientIdsForTrainer(user.id);
    if (!clientIds.includes(input.clientId)) {
      return { success: false as const, error: "Forbidden" };
    }
  }

  try {
    const program = await createProgramFromGeneratedPlan({
      aiPlan: input.aiPlan,
      trainerId: user.id,
      isTemplate: !input.clientId && input.isTemplate,
      aiGenerationParams: input.params,
      clientId: input.clientId || null,
      startDate: input.clientId
        ? (input.startDate ?? new Date().toISOString().split("T")[0])
        : null,
    });

    revalidatePath("/programs");
    if (input.clientId) revalidatePath(`/clients/${input.clientId}`);
    return { success: true as const, data: program.id };
  } catch (error) {
    console.error("Failed to save generated program:", error);
    const message =
      error instanceof Error && error.message.startsWith("Invalid generated program:")
        ? error.message
        : "Failed to save program";
    return {
      success: false as const,
      error: message,
    };
  }
}

export async function shareProgramViaEmailAction(
  programId: string,
  toEmail: string,
  ccRaw: string
): Promise<{ success: boolean; error?: string }> {
  const { userId } = await auth();
  if (!userId) return { success: false, error: "Unauthorized" };

  const dbUser = await prisma.user.findUnique({ where: { clerkId: userId } });
  if (!dbUser || dbUser.role !== "TRAINER") return { success: false, error: "Forbidden" };

  const program = await prisma.program.findUnique({
    where: { id: programId, trainerId: dbUser.id },
    select: {
      name: true,
      client: { select: { firstName: true, lastName: true } },
    },
  });
  if (!program) return { success: false, error: "Program not found" };

  const appBaseUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://inmotusrx.vercel.app";
  const pdfLink = `${appBaseUrl}/api/programs/${programId}/pdf`;
  const senderName = `${dbUser.firstName} ${dbUser.lastName}`;
  const clientName = program.client
    ? `${program.client.firstName} ${program.client.lastName}`
    : null;

  const recipients = parseShareRecipients(toEmail, ccRaw);

  try {
    await getResend().emails.send({
      from: process.env.RESEND_FROM_EMAIL ?? "noreply@inmotusrx.com",
      to: recipients,
      subject: `Your exercise plan: ${program.name}`,
      react: React.createElement(ShareProgramEmail, {
        programName: program.name,
        clientName,
        senderName,
        pdfLink,
      }),
    });
    return { success: true };
  } catch (err) {
    console.error("Failed to send share email:", err);
    return { success: false, error: "Failed to send email" };
  }
}

export async function copyGlobalProgramAction(globalProgramId: string) {
  const user = await getTrainerUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  try {
    const program = await programService.copyGlobalProgramToOrganization(
      globalProgramId,
      user.id
    );
    revalidatePath("/programs");
    return { success: true as const, data: { id: program.id } };
  } catch (error) {
    console.error("Failed to copy global program:", error);
    return { success: false as const, error: "Failed to copy program" };
  }
}

export async function getDistinctEquipmentAction(): Promise<{ success: true; data: string[] } | { success: false; error: string }> {
  try {
    const exercises = await prisma.exercise.findMany({
      where: { isActive: true },
      select: { equipmentRequired: true },
    })
    const all = exercises.flatMap(e => e.equipmentRequired)
    const distinct = [...new Set(all)]
      .filter(e => e && e.toLowerCase() !== 'none' && e.trim() !== '')
      .sort()
    return { success: true, data: distinct }
  } catch {
    return { success: false, error: 'Failed to load equipment list' }
  }
}
